# Generated by Django 4.2.24 on 2025-09-11 22:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("referrals", "0001_initial"),
        ("departments", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("patients", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="referral",
            name="from_doctor",
            field=models.ForeignKey(
                limit_choices_to={"role": "doctor"},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sent_referrals",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referrals",
                to="patients.patient",
            ),
        ),
        migrations.AddField(
            model_name="referral",
            name="to_department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_referrals",
                to="departments.department",
            ),
        ),
    ]
